on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Send to Nekoweb
    steps:
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: 'site'
          directory: 'neko'